---
- name: "Build a container with ansible"
  hosts: localhost
  connection: local
  tasks:
    - name: Log into Docker registry
      docker_login:
      registry_url: https://hub.docker.com/repository/docker/imas10/coming-soon-jenkins/general
      username: imas10
      password: azerty12345
  
    - name: stop current running container
      command: docker stop web-container
      ignore_errors: yes

    - name: remove stopped container
      command: docker rm web-container
      ignore_errors: yes

    - name: remove comingsoon-image
      command: docker rmi imas10/coming-soon-jenkins
      ignore_errors: yes

    - name: build docker image using the Dockerfile
      command: docker build -t imas10/coming-soon-jenkins:latest .
    
    - name: Push Image to dockerhub
      command: docker push imas10/coming-soon-jenkins:latest

    - name: run container
      command: docker run -d --name web-container -p 5000:80 imas10/coming-soon-jenkins

