---
- name: "Build a container with ansible"
  hosts: localhost
  connection: local
  tasks:
    - name: stop current running container
      command: docker stop web-container
      ignore_errors: yes

    - name: remove stopped container
      command: docker rm web-container
      ignore_errors: yes

    - name: remove comingsoon-image
      command: docker rmi comingsoon-pages
      ignore_errors: yes

    - name: build docker image using the Dockerfile
      command: docker build -t comingsoon-pages .

    - name: Log in to Docker Hub
      docker_login:
        username: imas10
        password: azerty12345
 
    - name: tag the docker image
      command: docker tag comingsoon-pages imas10/comingsoon-pages:0.0.01

    - name: Push Image to dockerhub
      command: docker push imas10/comingsoon-pages:0.0.01
    
    - name: run container
      command: docker run -d --name web-container -p 5000:80 comingsoon-pages
